title = "å­èˆ’çš„åšå®¢"
baseURL = ''

# This is what goes in <html lang="">
languageCode = 'en-us'

theme = "awesome"


# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next line
disqusShortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Posts'
    url = '/blog/'
    weight = 2
  [[menu.main]]
    name = 'Message'
    url = '/message/'
    weight = 3
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 4
  [[menu.main]]
    name = 'Lab'
    url = '/lab/'
    weight = 5

[params]
  sitename = "å­èˆ’çš„åšå®¢"
  defaultColor = "auto" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "æˆ‘æ˜¯å­èˆ’ã€‚å‰ç«¯ç¨‹åºå‘˜ï¼Œç‹¬ç«‹åšå®¢ä½œè€…ï¼Œéª‘è¡Œçˆ±å¥½è€…ï¼Œæ‘„å½±çˆ±å¥½è€…ï¼ŒINFJäººæ ¼ã€‚ç°åœ¨ç”Ÿæ´»å·¥ä½œåœ¨æ­å·ã€‚è¿™æ˜¯æˆ‘åœ¨é—²æš‡æ—¶é—´å†™çš„åšå®¢ï¼Œè®°å½•ç”Ÿæ´»ã€‚"
  mainSections = ['blog']
  toc = true # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatinated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).

[params.author]
  avatar = "" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "zishu.me ğŸ˜"
  name = "å­èˆ’"
  description = "æˆ‘æ˜¯å­èˆ’ã€‚/ å‰ç«¯ç¨‹åºå‘˜ï¼Œç‹¬ç«‹åšå®¢ä½œè€…ï¼Œéª‘è¡Œçˆ±å¥½è€…ï¼Œæ‘„å½±çˆ±å¥½è€…ï¼ŒINFJäººæ ¼ã€‚/  ç°åœ¨ç”Ÿæ´»å·¥ä½œåœ¨æ­å·ã€‚/  è¿™æ˜¯æˆ‘åœ¨é—²æš‡æ—¶é—´å†™çš„åšå®¢ï¼Œè®°å½•ç”Ÿæ´»ã€‚"

# Allow to override webmanifest options
[params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/zishume"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/Anghunk520"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[permalinks]
  blog = "/blog/:slug.html/"