baseURL = ""
languageCode = "en-us"
title = "å­èˆ’çš„åšå®¢"
theme = "meteor"  
paginate = 7
hasCJKLanguage = true
summaryLength = 99999

[markup]
  [markup.tableOfContents]  # æ–‡ç« ç›®å½•
    endLevel = 3
    ordered = false
  [markup.highlight]
    style ="github"    # é«˜äº®é£æ ¼
    lineNos = false         # æ˜¯å¦æ˜¾ç¤ºè¡Œå·
  [markup.goldmark]         # æ˜¯å¦åœ¨mdæ–‡ä»¶ä¸­æ¸²æŸ“htmlä»£ç 
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "zishu.me"
  logo = "https://img.zburu.com/author.png"
  author = "å­èˆ’"
  favicon = "https://img.zburu.com/favicon.png"
  buildDate = "2020-06-14"

[permalinks]
  blog = "/blog/:slug.html/"

[[params.socials]]
name = "ğŸ›Œå½’æ¡£"
link = "/blog/"

[[params.socials]]
name = "ğŸ“’ç•™è¨€æ¿"
link = "/message/"

[[params.socials]]
name = "ğŸ“¢å®éªŒå®¤"
link = "/lab/"

[[params.socials]]
name = "ğŸ˜’å…³äº"
link = "/about/"

[[params.socials]]
name = "ğŸ”Search"
link = "/search/"

[[params.socials]]
name = "ğŸŒRSS"
link = "/index.xml"
