baseURL = ""
languageCode = "en-us"
title = "å­èˆ’çš„åšå®¢"
theme = "v2ex"  #meteor
paginate = 10
hasCJKLanguage = true
summaryLength = 99999

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "zishu.me"
  logo = "https://imgurl.zishu.me/author.png"
  author = "å­èˆ’"
  favicon = "https://imgurl.zishu.me/favicon.ico"
  buildDate = "2020-06-14"
  twikooID = "https://twikoo.zishu.me/.netlify/functions/twikoo"

[permalinks]
  blog = "/blog/:slug.html/"

[[params.socials]]
name = "å­èˆ’çš„åšå®¢ğŸ˜"
link = "/"

[[params.socials]]
name = "å½’æ¡£"
link = "/blog/"

[[params.socials]]
name = "ç•™è¨€æ¿"
link = "/message/"

[[params.socials]]
name = "å®éªŒå®¤"
link = "/lab/"

[[params.socials]]
name = "å…³äº"
link = "/about/"

[[params.socials]]
name = "æœç´¢"
link = "/search/"

[[params.socials]]
name = "éª‘è¡Œ"
link = "/riding/"